name       : kicad-templates
version    : 7.0.6
release    : 5
source     :
    - https://gitlab.com/kicad/libraries/kicad-templates/-/archive/7.0.6/kicad-templates-7.0.6.tar.gz : 65a6b94fb1bb641f6a0130e6b3d4be0f8294e84b4bbbff0b294e2532782ac2f5
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
