name       : kicad-templates
version    : 5.0.0
release    : 1
source     :
    - https://github.com/KiCad/kicad-templates/archive/5.0.0.tar.gz : 5259eca6d7b4519258a6cfd7d9e90b5eeeaa6ab6975ad0b12734f7bca1210cb6
license    : CC-BY-SA-4.0
component  : office
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
