name       : kicad-templates
version    : 5.1.2
release    : 2
source     :
    - https://github.com/KiCad/kicad-templates/archive/5.1.2.tar.gz : fd14978af2d5b64d41561c8cd954f386a10e1548d6db2d4998281deffddeffbb
license    : CC-BY-SA-4.0
component  : office
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
