name       : kicad-templates
version    : 5.1.12
release    : 4
source     :
    - https://gitlab.com/kicad/libraries/kicad-templates/-/archive/5.1.12/kicad-templates-5.1.12.tar.bz2 : 4afcf871b7f0c6d55d07deb8f13106861495a6166fd49edd8b18b5d952974e16
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
