name       : kicad-templates
version    : 5.1.6
release    : 3
source     :
    - https://github.com/KiCad/kicad-templates/archive/5.1.6.tar.gz : f970e889ed3c909691f8a2464831e117e0002cfb0d3b3558bf16f42fa04c55dc
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %make_install
